# account-service/src/main/resources/application.yml
server:
  port: 8081

spring:
  config:
    import: "nacos:account-service.yaml"
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/ai_customer_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



mybatis:
  configuration:
    map-underscore-to-camel-case: true

