server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 添加以下配置
        namespace: ""
        register-enabled: true
    gateway:
      # 全局CORS配置
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: account-service
          uri:  http://localhost:8081
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=1
        - id: qa-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/qa/**
          filters:
            - StripPrefix=1
        - id: history-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/history/**
          filters:
            - StripPrefix=1
        - id: knowledge-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/knowledge/**
          filters:
            - StripPrefix=1
      loadbalancer:
        ribbon:
          enabled: false
        cache:
          enabled: false

# 添加日志配置以便调试
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
